[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -c \"import os; port = int(os.environ.get('PORT', '8000')); from uvicorn.main import run; run('app.main:app', host='0.0.0.0', port=port, proxy_headers=True)\""
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
ENVIRONMENT = "production"
_USE_HTTPS = "true"
_ALLOWED_HOSTS = "mindbeat-production.up.railway.app"
