[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = ""  # Let Dockerfile handle the start command
healthcheckPath = "/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.env]
PORT = "8000"
ENVIRONMENT = "production"
USE_HTTPS = "true"
ALLOWED_HOSTS = "*.railway.app"
