[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'uvicorn app.main:app --host 0.0.0.0 --port ${PORT}'"  # Use shell for env var expansion
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.env]
ENVIRONMENT = "production"
_USE_HTTPS = "true"
_ALLOWED_HOSTS = "*.railway.app"
