[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.env]
PORT = "8000"
ENVIRONMENT = "production"
USE_HTTPS = "true"
ALLOWED_HOSTS = "*.railway.app"
